### ISSUE TITLE
How to Set bounds for ql-tooltip in ReactQuill?

### ISSUE THREAD

**Issue by KonceptTW** [VaguelySerious/react-quill#10]
### ReactQuill version

- [x] master
- [ ] v2.0.0-beta.2
- [ ] v2.0.0-beta.1
- [ ] 1.3.5
- [ ] 1.3.4 or older
- [ ] Other (fork)

[https://codesandbox.io/p/sandbox/react-quill-template-forked-zw2tng](https://codesandbox.io/p/sandbox/react-quill-template-forked-zw2tng)

I have a ReactQuill component wrapped in a container with overflow-y: auto, but due to this, the ql-tooltip gets clipped when it pops out.

I want to set the bounds within the editingAreaRef.

I tried using bounds={quillRef.current?.editingAreaRef?.current}, but this causes the page to not render properly.

Is there a way to achieve the desired behavior?

**Comment by VaguelySerious** [comment]
@KonceptTW Thanks for providing a code sandbox! This seems like a general CSS issue, unrelated with react-quill. `overflow-auto` _will_ restrict overflow, and it's doing that just as intended. Presumably you're setting the overflow to auto because you want something to scroll. The question you should ask yourself is: what exactly do I want to scroll? If you want to just scroll the text content of the quill editor, then add a CSS rule:
```css
.ql-editor {
  overflow: auto;
}
```

Trying this on your sandbox fixes the overflow.

**Comment by KonceptTW** [comment]
Hi, @VaguelySerious thanks for reply,

I didn’t describe my situation clearly before.

ReactQuill is inside a width-limited Drawer, and besides ReactQuill, there are other fields above and below it.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/a4a75d66-9ebf-4404-87f0-f131b3a4311f">

You suggested setting .ql-editor to overflow: auto, but I noticed that .ql-editor already has this setting by default, so I'm not sure what you meant by that.

Could you clarify?

<img width="400" alt="image" src="https://github.com/user-attachments/assets/f8a8ce12-fab5-44aa-8342-e6955a6d9b0b">

p.s: codesandbox example updated

**Comment by VaguelySerious** [comment]
@KonceptTW I see. Maybe I'm not understanding what it is you're trying to do. Can you describe what you were trying to achieve when you added `overflow-y: auto` to the container surrounding react-quill?

**Comment by KonceptTW** [comment]
The react-quill component is inside a drawer.

At the top of the drawer, there is a button to close the drawer, and at the bottom, there is a button to update the edited content. The middle section is the editing area, but its content exceeds the window height, so an internal scrollbar is necessary.
<img width="400" alt="image" src="https://github.com/user-attachments/assets/3cd2b0d0-cabc-438e-8e3a-f0042614703b">



I checked the issues in the **Quill** project and found that others suggested using bounds to restrict the boundaries of the tooltips.

However, whether I assign **ref.current** or **.ql-container** as the parameter for bounds, it doesn't seem to work.

[https://github.com/slab/quill/issues/1238#issuecomment-514879754](https://github.com/slab/quill/issues/1238#issuecomment-514879754)

**Comment by VaguelySerious** [comment]
@KonceptTW Ah, in that case, try:
```css
.ql-container {
  max-height: 100px; # your choice
}
.ql-editor {
  max-height: 100px; # your choice, should be same as above
  min-height: unset;
  overflow-y: scroll;
}
```

and make sure the CSS is specific enough to overwrite Quill's base styles. When I apply this to your updates code sanbox, it limits the editor size, and allows scrolling, without blocking the tooltip from overflowing horizontally.
