### ISSUE TITLE
Error: domains - http://deefauph.com,https://theeptoah.com, action - /event, error- Failed to fetch

### ISSUE THREAD

**Issue by chayangkoon10** [VaguelySerious/react-quill#12]
I got this error message on my web page, how can I fix it?
`Unhandled Runtime Error
Error: domains - http://deefauph.com,https://theeptoah.com, action - /event, error- Failed to fetch`

**Comment by VaguelySerious** [comment]
It does not seem like the issue you're seeing is related to this NPM package. May I suggest searching your codebase for the domains you listed and where they might be called from? Also try disabling all your browser plugins or using a different browser to see if the issues persist
