### ISSUE TITLE
Cannot destructure property 'delta' of 'this.regenerationSnapshot' as it is undefined.

### ISSUE THREAD

**Issue by kuhnflyfish** [VaguelySerious/react-quill#13]
<img width="971" alt="Screenshot 2024-11-01 at 1 10 47 PM" src="https://github.com/user-attachments/assets/5bd90baf-2006-4256-91e1-f885d3487a26">

Recently had to upgrade to react-quill-new from react-quill.  Installed react-quill-new@3.3.3 and this error is stemming from ComponentDidUpdate.  Any ideas as to why?

**Comment by VaguelySerious** [comment]
No idea from just the error message itself. Can you share a minimal reproducible example on code sandbox or similar? Usually in the process of narrowing down the example you'll find you issue.

**Comment by kuhnflyfish** [comment]
So apparently it doesn't like the `modules` prop anymore.  I removed that and error disappeared.

**Comment by kuhnflyfish** [comment]
Issue resolved after removing the `modules` prop
