### ISSUE TITLE
No such file or directory "quill.snow.css.map"

### ISSUE THREAD

**Issue by NonthapatKim** [VaguelySerious/react-quill#18]
Hello,

Error: ENOENT: no such file or directory, open '../node_modules/react-quill-new/dist/quill.snow.css.map'

When building or running on prod, I guess there will be a problem here. Is there a solution?

**Comment by VaguelySerious** [comment]
@NonthapatKim This should not be a problem - it will only affect the developer tools.

If you want to remove the warning, import `quill.snow.css` from `../node_modules/react-quill-new/node_modules/quill/dist/quill.snow.css` instead

**Comment by NonthapatKim** [comment]
Thank !
