### ISSUE TITLE
An error occurred while trying to read the map file at quill.snow.css.map

### ISSUE THREAD

**Issue by 5M7-Api** [VaguelySerious/react-quill#9]
When I run my project using vite in a nodejs environment, the following error occurs.

**Failed to load source map for C:/(files path)/node_modules/react-quill-new/dist/quill.snow.css.**

**Error: An error occurred while trying to read the map file at quill.snow.css.map**

**Error: ENOENT: no such file or directory, open 'C:\(files path)\node_modules\react-quill-new\dist\quill.snow.css.map'**

But when I tested the functionality of the rich text editor, there were no obvious anomalies or errors in the style or operation process.

package version:

- nodeJs v20.10.0
- react v18.3.1
- vite v5.2.11

**Comment by VaguelySerious** [comment]
The sourcemap file (`quill.snow.css.map`) isn't required for normal operation, and this npm package currently doesn't re-export the sourcemap files.

If you just want the error to go away, you can import the CSS file from `react-quill-new/node_modules/quill/dist/quill.snow.css` instead, where a matching map file is defined.

**Comment by 5M7-Api** [comment]
> The sourcemap file (`quill.snow.css.map`) isn't required for normal operation, and this npm package currently doesn't re-export the sourcemap files.
> 
> If you just want the error to go away, you can import the CSS file from `react-quill-new/node_modules/quill/dist/quill.snow.css` instead, where a matching map file is defined.

Thanks for your help. When I tried to build the project, I got the following error.

![image](https://github.com/user-attachments/assets/13ad67a1-0492-4565-87db-815b1024339d)

I reinstalled the react-quill(`npm install react-quill --save`) package to solve this problem.  I wonder if my solution is correct? Is this error expected?

**Comment by VaguelySerious** [comment]
You're probably importing `react-quill` somewhere, when you should be importing `react-quill-new` instead

**Comment by 5M7-Api** [comment]
> You're probably importing `react-quill` somewhere, when you should be importing `react-quill-new` instead

I found the error in the vite configuration file and have successfully built it. Thank you for your patient help.

**Comment by justintoman** [comment]
> I found the error in the vite configuration file and have successfully built it. Thank you for your patient help.

@5M7-Api  What was the error? I'm experiencing this too and I don't know what's wrong.

**Comment by 5M7-Api** [comment]
> > I found the error in the vite configuration file and have successfully built it. Thank you for your patient help.
> 
> @5M7-Api What was the error? I'm experiencing this too and I don't know what's wrong.

The error is in the configuration of vite, the code is as follows.

`        manualChunks: {
          lodash: ["lodash"],
          axios: ["axios"],
          "mui-x-dgrid": ["@mui/x-data-grid"],
          "mui-x-dpick": ["@mui/x-date-pickers"],
          "mui-icons": ["@mui/icons-material"],
          "mui-color-input": ["mui-color-input"],
          echarts: ["echarts", "echarts-for-react"],
          konva: ["konva", "react-konva"],
          quill: ["react-quill-new", "@ssumo/quill-resize-module"],
          "grid-layout": ["react-grid-layout"],
        },
`
